default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: wolo

development:
  <<: *default
  database: hospitable_development

test:
  <<: *default
  database: hospitable_test

production:
  <<: *default
  database: hospitable_production
